branches:
  only:
    - development

language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules
    - typings


env:
  global:
  - GH_REF: github.com/prijindal/prijindal.github.io.git
  
notifications:
  # slack:

script:
  - echo "Test Completed"
  - npm run gh-deploy
