branches:
  only:
    - development

language: node_js
node_js:
  - "8"

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

env:
  global:
  - GH_REF: github.com/prijindal/prijindal.github.io.git
  - GH_EMAIL: priyanshujindal1995@gmail.com
  - GH_NAME: Travis CI

notifications:
  # slack:

before_install:
  - openssl aes-256-cbc -K $encrypted_efd26535d89e_key -iv $encrypted_efd26535d89e_iv -in id_rsa.enc -out id_rsa -d
  - chmod 600 id_rsa

install:
  - yarn
script:
  - yarn lint
  - yarn test --watch=false --browsers ChromeHeadless
after_success:
  - npm run build:ssr
  - sh render-deploy.sh
  - scp -i id_rsa -o "StrictHostKeyChecking=no" -r dist ubuntu@13.126.205.26:~/prijindal/source/ 
deploy:
  - provider: pages
    local-dir: dist/browser
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: true
    target-branch: master
    on:
      branch: development
      
  - provider: firebase
    token: $FIREBASE_TOKEN
    skip-cleanup: true
    on:
      branch: development