branches:
  only:
    - angular2

language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules
    - typings

notifications:
  # slack:

script:
  - echo "Test Completed"
  - npm run github-deploy:prod
