branches:
  only:
    - development

language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules

env:
  global:
  - GH_REF: git@github:prijindal/prijindal.github.io.git
  - GH_EMAIL: priyanshujindal1995@gmail.com
  - GH_NAME: Travis CI

notifications:
  # slack:

script:
  - echo "Test Completed"
  - npm run gh-deploy
