branches:
  only:
    - development

language: node_js
node_js:
  - "8"

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

env:
  global:
  - GH_REF: github.com/prijindal/prijindal.github.io.git
  - GH_EMAIL: priyanshujindal1995@gmail.com
  - GH_NAME: Travis CI

notifications:
  # slack:

install:
  - yarn
script:
  - yarn lint
  - yarn test --watch=false --browsers ChromeHeadless
after_success:
  - ng build --prod --aot
deploy:
  provider: pages
  local-dir: dist/browser
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target-branch: master
  on:
    branch: development
